version: "3.9"

services:
    mariadbtodolist:
        container_name: mariadbtodolist
        build: ./mariadb
        volumes:
            - ./mariadb/db:/var/lib/mysql
        restart: always
        env_file:
            - .env
        command: 
            - "--default-authentication-plugin=mysql_native_password"
        networks:
            - todolist-network
        ports:
            - 8062:3306
    phpmyadmintodolist:
        container_name: phpmyadmintodolist
        build: ./phpmyadmin
        depends_on:
            - mariadbtodolist
        environment:
            - PMA_HOST=mariadbtodolist
            - PMA_PORT=3306
            #- PMA_ARBITRARY=1 # exige conexion https
        restart: always
        networks:
            - todolist-network
        ports:
            - 8060:80
        #    - 8062:443
        expose:
            - 80
        #    - 443
    nodetodolist:
        container_name: nodetodolist
        build: ./node
        depends_on:
            - mariadbtodolist
        volumes:
            - ./node:/api_node
        ports:
            - 8061:8080
        expose:
            - "8080"
        restart: always
        env_file:
            - .envNode
        networks:
            - todolist-network
networks:
    todolist-network:
        driver: bridge
volumes:
    node:
    db: